// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://naveyamyfmrheezsvltn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5hdmV5YW15Zm1yaGVlenN2bHRuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMwOTExMDYsImV4cCI6MjA2ODY2NzEwNn0.7GQjvul12xxQdapj_wxVvgpZxhVmhc7WAcWrJO9q-UI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});